### ISSUE TITLE
security issue with evaling arbitrary strings

### ISSUE THREAD

**Issue by tobyink** [perlancar/perl-Regexp-From-String#1]
This can be seen using:

```shell
echo "Hello, world" > hello.txt
perl -MRegexp::From::String=str_maybe_to_re -E'say str_maybe_to_re("qr() and unlink q(hello.txt) and qr()")'
cat hello.txt
```

Compare this with Regexp::Util's `deserialize_regexp`:

```shell
echo "Hello, world" > hello.txt
perl -MRegexp::Util=:all -E'say deserialize_regexp("qr() and unlink q(hello.txt) and qr()")'
cat hello.txt
```

I'd suggest either documenting it as a potential security issue, or using Safe.pm to eval the regexp.

**Comment by perlancar** [comment]
I plan to add a safety option with several choices:
- 0: no check, as before, with documenting security issue
- 1: forbid any literal `)` in the string of `qr(...)` form and any literal `/` in the string of `/.../` form, which might be rather annoyingly restrictive.
- 2: Safe.pm evaling, like in Regexp::Util (or just use Regexp::Util)

Don't know which default to choose yet. Probably choice 1. I'm using this for convenience in CLI, so the regexes tend to be simple. There are two choices of delimiters `/.../` and `qr(...)` so I'm predicting most of the time I will be using `/.../` without involving `/` in the pattern.

Do you think there are tricks to work around choice 1?

**Comment by tobyink** [comment]
A regex can include Perl code via `?{ ... }`

**Comment by perlancar** [comment]
> A regex can include Perl code via `?{ ... }`

Ah, of course. I'm adding restriction for literal `(?{` and `(??{` too.

Commit 481162f
